import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateVacationToRanges1750194769248 implements MigrationInterface {
    name = 'UpdateVacationToRanges1750194769248'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP COLUMN \`date\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD \`startDate\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD \`endDate\` date NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`color\` \`color\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`mileage\` \`mileage\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`insurance_expiry_date\` \`insurance_expiry_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`technical_revision_expiry_date\` \`technical_revision_expiry_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`photo_url\` \`photo_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`photo_public_id\` \`photo_public_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`acquisition_date\` \`acquisition_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`last_maintenance_date\` \`last_maintenance_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`next_maintenance_date\` \`next_maintenance_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`photoUrl\` \`photoUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`photoPublicId\` \`photoPublicId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_c0354a9a009d3bb45a08655ce3b\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_1cffb00d43787a8f9c4114223e1\``);
        await queryRunner.query(`ALTER TABLE \`comment\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`comment\` CHANGE \`reportId\` \`reportId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`report\` DROP FOREIGN KEY \`FK_e347c56b008c2057c9887e230aa\``);
        await queryRunner.query(`ALTER TABLE \`report\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_73da89094904a250204b3a6081f\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_76e7ee45e3ed03009858472f8a5\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_7bbb60183800e879e83b60c350a\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_0dbb224ec2a7aa05c2a464e510b\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`firstApprovedDate\` \`firstApprovedDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`secondApprovedDate\` \`secondApprovedDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`approvedDate\` \`approvedDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejectionReason\` \`rejectionReason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejectedDate\` \`rejectedDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`first_approved_by\` \`first_approved_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`second_approved_by\` \`second_approved_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`approved_by\` \`approved_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejected_by\` \`rejected_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birthDate\` \`birthDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginIp\` \`lastLoginIp\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginDate\` \`lastLoginDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`photo_url\` \`photo_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`photo_public_id\` \`photo_public_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`google_id\` \`google_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`from_location\` \`from_location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`to_location\` \`to_location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`expected_return_date\` \`expected_return_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`actual_return_date\` \`actual_return_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`person_responsible\` \`person_responsible\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`assigned_date\` \`assigned_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`returned_date\` \`returned_date\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`performed_by\` \`performed_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`cost\` \`cost\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`amenities\` \`amenities\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`rules\` \`rules\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`photoUrl\` \`photoUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`photoPublicId\` \`photoPublicId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_2ed63d2512e9a3dd4a78c614402\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_38a4956b6b5d7d562718bf2957e\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_04b43e2ea9d3a7224b0ca4701c2\``);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`inventory_id\` \`inventory_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`vehicle_id\` \`vehicle_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`housing_id\` \`housing_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`rental_comments\` \`rental_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`rental_metadata\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`rental_metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_c0354a9a009d3bb45a08655ce3b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_1cffb00d43787a8f9c4114223e1\` FOREIGN KEY (\`reportId\`) REFERENCES \`report\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`report\` ADD CONSTRAINT \`FK_e347c56b008c2057c9887e230aa\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_73da89094904a250204b3a6081f\` FOREIGN KEY (\`first_approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_76e7ee45e3ed03009858472f8a5\` FOREIGN KEY (\`second_approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_7bbb60183800e879e83b60c350a\` FOREIGN KEY (\`approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_0dbb224ec2a7aa05c2a464e510b\` FOREIGN KEY (\`rejected_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_2ed63d2512e9a3dd4a78c614402\` FOREIGN KEY (\`inventory_id\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_38a4956b6b5d7d562718bf2957e\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_04b43e2ea9d3a7224b0ca4701c2\` FOREIGN KEY (\`housing_id\`) REFERENCES \`housing\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_04b43e2ea9d3a7224b0ca4701c2\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_38a4956b6b5d7d562718bf2957e\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP FOREIGN KEY \`FK_2ed63d2512e9a3dd4a78c614402\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_0dbb224ec2a7aa05c2a464e510b\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_7bbb60183800e879e83b60c350a\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_76e7ee45e3ed03009858472f8a5\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP FOREIGN KEY \`FK_73da89094904a250204b3a6081f\``);
        await queryRunner.query(`ALTER TABLE \`report\` DROP FOREIGN KEY \`FK_e347c56b008c2057c9887e230aa\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_1cffb00d43787a8f9c4114223e1\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_c0354a9a009d3bb45a08655ce3b\``);
        await queryRunner.query(`ALTER TABLE \`rental\` DROP COLUMN \`rental_metadata\``);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD \`rental_metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`rental_comments\` \`rental_comments\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`housing_id\` \`housing_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`vehicle_id\` \`vehicle_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` CHANGE \`inventory_id\` \`inventory_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_04b43e2ea9d3a7224b0ca4701c2\` FOREIGN KEY (\`housing_id\`) REFERENCES \`housing\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_38a4956b6b5d7d562718bf2957e\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental\` ADD CONSTRAINT \`FK_2ed63d2512e9a3dd4a78c614402\` FOREIGN KEY (\`inventory_id\`) REFERENCES \`inventory\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`photoPublicId\` \`photoPublicId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`photoUrl\` \`photoUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`rules\` \`rules\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`housing\` CHANGE \`amenities\` \`amenities\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`cost\` \`cost\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`performed_by\` \`performed_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`maintenance_history\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`returned_date\` \`returned_date\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_projects\` CHANGE \`assigned_date\` \`assigned_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`person_responsible\` \`person_responsible\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`actual_return_date\` \`actual_return_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`expected_return_date\` \`expected_return_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`to_location\` \`to_location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory_movements\` CHANGE \`from_location\` \`from_location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`google_id\` \`google_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`photo_public_id\` \`photo_public_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`photo_url\` \`photo_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginDate\` \`lastLoginDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginIp\` \`lastLoginIp\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birthDate\` \`birthDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejected_by\` \`rejected_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`approved_by\` \`approved_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`second_approved_by\` \`second_approved_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`first_approved_by\` \`first_approved_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejectedDate\` \`rejectedDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`rejectionReason\` \`rejectionReason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`approvedDate\` \`approvedDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`secondApprovedDate\` \`secondApprovedDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`firstApprovedDate\` \`firstApprovedDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_0dbb224ec2a7aa05c2a464e510b\` FOREIGN KEY (\`rejected_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_7bbb60183800e879e83b60c350a\` FOREIGN KEY (\`approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_76e7ee45e3ed03009858472f8a5\` FOREIGN KEY (\`second_approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD CONSTRAINT \`FK_73da89094904a250204b3a6081f\` FOREIGN KEY (\`first_approved_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`report\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`report\` ADD CONSTRAINT \`FK_e347c56b008c2057c9887e230aa\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` CHANGE \`reportId\` \`reportId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comment\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_1cffb00d43787a8f9c4114223e1\` FOREIGN KEY (\`reportId\`) REFERENCES \`report\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_c0354a9a009d3bb45a08655ce3b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`photoPublicId\` \`photoPublicId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`photoUrl\` \`photoUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`next_maintenance_date\` \`next_maintenance_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`last_maintenance_date\` \`last_maintenance_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`inventory\` CHANGE \`acquisition_date\` \`acquisition_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`photo_public_id\` \`photo_public_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`photo_url\` \`photo_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`technical_revision_expiry_date\` \`technical_revision_expiry_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`insurance_expiry_date\` \`insurance_expiry_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`mileage\` \`mileage\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vehicle\` CHANGE \`color\` \`color\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` DROP COLUMN \`startDate\``);
        await queryRunner.query(`ALTER TABLE \`vacation\` ADD \`date\` date NOT NULL`);
    }

}
